auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Reduci.com
url:              http://legendsland.github.com
feed:             /atom.xml
author:
    name:         Reduci
    twitter:      twitter.com/legendsland
description:      "Reduci\'s Blog"
author_info:      <a href="http://legendsland.github.com/about">Reduci</a>

