
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "backup"]
auto:          true
markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: []

kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

textile_ext:   textile
pygments:         true
paginate:         6
permalink:        /:categories/:title 

title:           
feed:             /atom.xml
author:
    name:     "Yiannis Chang"
    email:    yiannis.chang@gmail.com
# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://legendsland.github.io

